import Head from "next/head";
import { Component } from "react";
import { Form, InlineInput, Input, Select, Switch } from "../components/forms";
import { Container, Flex, Grid } from "../components/utils";
import { Alert, Badge, Button } from "../components/view";

export default class Home extends Component {
  constructor(props) {
    super(props);
    this.colors = [
      "primary",
      "secondary",
      "info",
      "success",
      "warning",
      "danger",
      "light",
      "dark",
    ];

    // Alerts
    this.alerts = this.colors.map((item) => {
      return (
        <Alert
          color={item}
          key={item}
          flushed={Math.random() > 0.5 ? true : false}
          modern={Math.random() > 0.5 ? true : false}
        >
          This is the {item} alert with out a link!
        </Alert>
      );
    });

    // Badges
    this.badges = this.colors.map((item) => {
      return (
        <Badge
          key={item}
          color={item}
          outline={Math.random() > 0.5 ? true : false}
        >
          {item}
        </Badge>
      );
    });

    // Buttons
    this.buttons = this.colors.map((item) => {
      return (
        <Button
          key={item}
          color={item}
          outline={Math.random() > 0.5 ? true : false}
        >
          {item}
        </Button>
      );
    });
  }

  render() {
    return (
      <Container>
        <Head>
          <title>Evolution UI</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <h1 className="text-6xl font-bold text-gradient text-gradient-light mb-8">
          Evolution UI
        </h1>

        <section className="mb-8" title="Forms">
          <h2 className="text-4xl font-bold text-gradient text-gradient-info mb-8">
            Forms
          </h2>

          <Form mathod="post">
            <Input
              id="name"
              label="Name"
              type="text"
              name="fullName"
              placeholder="Full Name"
            />

            <Input
              id="email"
              label="Email"
              type="email"
              name="email"
              placeholder="Email Address"
              floating
            />

            <Input
              id="password"
              label="Password"
              type="password"
              name="password"
              placeholder="Password"
              flushed
              floating
            />

            <Select id="country" label="Country" placeholder="Country">
              <option value="0">Select Country</option>
              <option value="1">USA</option>
              <option value="2">UK</option>
              <option value="3">China</option>
            </Select>

            <Flex>
              <InlineInput id="g1" label="Male" type="radio" name="gender" />
              <InlineInput id="g2" label="Female" type="radio" name="gender" />
            </Flex>

            <InlineInput id="r" label="Remeber me" type="checkbox" name="r" />

            <Switch id="x" label="Change password on logon" name="x" />

            <Button type="submit" color="primary">
              Register
            </Button>
          </Form>
        </section>

        <section className="mb-8" title="Alerts">
          <h2 className="text-4xl font-bold text-gradient text-gradient-info mb-8">
            Alerts
          </h2>
          <Grid>
            {this.alerts}

            <Alert color="info" flushed>
              This is a flushed alert with out a link!
            </Alert>
            <Alert color="success" modern>
              <Badge color="success" pill>
                New
              </Badge>
              This is a modern alert with a badge component!
            </Alert>
          </Grid>
        </section>

        <section className="mb-8" title="Badges">
          <h2 className="text-4xl font-bold text-gradient text-gradient-info mb-8">
            Badges
          </h2>

          <Flex>{this.badges}</Flex>
        </section>

        <section className="mb-8" title="Buttons">
          <h2 className="text-4xl font-bold text-gradient text-gradient-info mb-8">
            Buttons
          </h2>

          <Flex>{this.buttons}</Flex>
        </section>
      </Container>
    );
  }
}
