import Head from "next/head";
import { Component } from "react";
import {
  Alert,
  Badge,
  Button,
  Card,
  CardBody,
  CardFooter,
} from "../components/view";
import { Container, Flex, Grid } from "../components/utils";
import { InlineInput, Input, Select, Switch } from "../components/forms";

export default class Home extends Component {
  constructor(props) {
    super(props);
    this.colors = [
      "primary",
      "secondary",
      "info",
      "success",
      "warning",
      "danger",
      "light",
      "dark",
    ];
  }

  render() {
    return (
      <Container>
        <Head>
          <title>NextEvolution, Evolution UI in Next.js</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <header className="mb-8 text-center">
          <h1 className="text-5xl sm:text-7xl lg:text-8xl 2xl:text-9xl font-bold text-gradient text-gradient-info mb-8">
            Next Evolution
          </h1>

          <p className="text-3xl font-semibold text-gradient text-gradient-info">
            Evolution UI in Next.js
          </p>
        </header>

        <section className="mb-8 text-slate-800" title="Forms">
          <h2 className="text-4xl font-bold text-gradient text-gradient-info mb-8">
            Forms
          </h2>

          <div className="mb-8">
            <h3 className="text-3xl font-bold mb-6">Basic</h3>
            <Input
              id="email"
              label="Email address"
              type="email"
              name="email"
              helpText="We'll never share your email with anyone else."
            />
            <Input
              id="password"
              type="password"
              name="password"
              label="Password"
            />
            <InlineInput
              id="check"
              name="check"
              type="checkbox"
              label="Check me out"
            />

            <h4 className="text-2xl mb-4">Radio buttons</h4>

            <InlineInput
              id="radio1"
              type="radio"
              name="radio"
              label="Default radio"
            />
            <InlineInput
              id="radio2"
              type="radio"
              name="radio"
              label="Another radio"
            />

            <Select id="country" label="Select input" placeholder="Country">
              <option value="0">Open this select menu</option>
              <option value="1">One</option>
              <option value="2">Two</option>
              <option value="3">Three</option>
            </Select>

            <Input id="upload" type="file" name="upload" label="Upload" />

            <Switch id="x" label="Switch checkbox input" name="x" />

            <Button type="submit" color="primary">
              Submit
            </Button>
          </div>

          <div className="mb-8">
            <h3 className="text-3xl font-bold mb-6">Floating labels</h3>
            <Input
              id="email1"
              label="Email"
              type="email"
              name="email"
              placeholder="Email Address"
              floating
            />
            <Input
              id="password1"
              label="Password"
              type="password"
              name="password"
              placeholder="Password"
              floating
            />
          </div>

          <div>
            <h3 className="text-3xl font-bold mb-6">Flushed</h3>
            <Input
              id="email2"
              label="Email"
              type="email"
              name="email"
              placeholder="Email Address"
              flushed
              floating
            />
            <Input
              id="password2"
              label="Password"
              type="password"
              name="password"
              placeholder="Password"
              flushed
              floating
            />
          </div>
        </section>

        <section className="mb-8 text-slate-800" title="Components">
          <h2 className="text-4xl font-bold text-gradient text-gradient-info mb-8">
            Components
          </h2>

          <div className="mb-8" title="Alerts">
            <h3 className="text-3xl font-bold mb-6">Alerts</h3>

            <div className="grid gap-4 mb-4">
              <h4 className="text-2xl">Basic</h4>
              {this.colors.map((item) => {
                return (
                  <Alert key={item} color={item}>
                    This is the {item} alert without a link!
                  </Alert>
                );
              })}

              <h4 className="text-2xl">Flushed</h4>

              <Alert color="info" flushed>
                This is a flushed alert without a link!
              </Alert>

              <h4 className="text-2xl">Modern</h4>

              <Alert color="info" modern>
                <Badge color="info" pill>
                  New
                </Badge>
                This is a modern alert with a badge component!
              </Alert>
            </div>
          </div>

          <div className="mb-8" title="Badges">
            <h3 className="text-3xl font-bold mb-6">Badges</h3>

            <h4 className="text-2xl mb-4">Basic</h4>

            <Flex>
              {this.colors.map((item) => {
                return (
                  <Badge key={item} color={item}>
                    {item}
                  </Badge>
                );
              })}
            </Flex>

            <h4 className="text-2xl mb-4">Outline</h4>

            <Flex>
              {this.colors.map((item) => {
                return (
                  <Badge key={item} color={item} outline>
                    {item}
                  </Badge>
                );
              })}
            </Flex>
          </div>

          <div className="mb-8" title="Buttons">
            <h3 className="text-3xl font-bold mb-6">Buttons</h3>

            <h4 className="text-2xl mb-4">Basic</h4>

            <Flex>
              {this.colors.map((item) => {
                return (
                  <Button key={item} color={item}>
                    {item}
                  </Button>
                );
              })}
            </Flex>

            <h4 className="text-2xl mb-4">Outline</h4>

            <Flex>
              {this.colors.map((item) => {
                return (
                  <Button key={item} color={item} outline>
                    {item}
                  </Button>
                );
              })}
            </Flex>
          </div>

          <div className="mb-8" title="Cards">
            <h3 className="text-3xl font-bold mb-6">Cards</h3>

            <h4 className="text-2xl mb-4">Basic</h4>

            <Grid>
              <Card>
                <CardBody>
                  <h1 className="text-5xl font-bold text-gradient text-gradient-primary mb-8">
                    Next Evolution
                  </h1>
                  <h2 className="text-2xl font-light mb-4">
                    Evolution UI in Next.js
                  </h2>
                  <p className="mb-4">
                    Lorem ipsum dolor sit amet consectetur adipisicing elit.
                    Dolorem veniam suscipit sed autem animi culpa dolores
                    voluptatibus dolore, fuga beatae eaque. Laudantium expedita
                    earum itaque animi voluptatibus enim quasi explicabo.
                  </p>
                  <Button color="primary">Read more...</Button>
                </CardBody>
              </Card>

              <Card>
                <CardBody>
                  <h1 className="text-5xl font-bold text-gradient text-gradient-info mb-8">
                    Evolution UI
                  </h1>
                  <h2 className="text-2xl font-light mb-4">
                    Build modern UIs in no time
                  </h2>
                  <p className="mb-4">
                    Lorem ipsum dolor sit amet consectetur adipisicing elit.
                    Obcaecati quos, minima, earum error culpa eius repudiandae
                    aspernatur tempore id quis voluptates inventore ullam.
                    Laborum voluptates nihil saepe. Praesentium, recusandae
                    voluptas?
                  </p>
                  <Button color="info">Read more...</Button>
                </CardBody>
              </Card>
            </Grid>
          </div>
        </section>
      </Container>
    );
  }
}
